name: Build and Release

on:
  push:
    tags:
      - '*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release'
        required: true
        type: string

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install uv
      uses: astral-sh/setup-uv@v3
    
    - name: Install dependencies
      run: uv sync
    
    - name: Build addon
      run: python build.py
    
    - name: Get built addon filename
      id: get_filename
      shell: powershell
      run: |
        $addonFile = Get-ChildItem -Name "*.nvda-addon" | Select-Object -First 1
        echo "filename=$addonFile" >> $env:GITHUB_OUTPUT
        echo "$addonFile"
    
    - name: Create Release
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: ${{ steps.get_filename.outputs.filename }}
        generate_release_notes: true
        draft: false
        prerelease: false
    
    - name: Create Manual Release
      if: github.event_name == 'workflow_dispatch'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.event.inputs.version }}
        name: Release ${{ github.event.inputs.version }}
        files: ${{ steps.get_filename.outputs.filename }}
        generate_release_notes: true
        draft: false
        prerelease: false
    
    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: nvda-addon
        path: ${{ steps.get_filename.outputs.filename }}